name: Deploy CyberSentinel AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start Backend Server
      run: |
        python -m uvicorn backend:app --host 0.0.0.0 --port 8000 &
        
    - name: Start Frontend Server
      run: |
        python -m streamlit run frontend.py --server.port 8501 &